# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import CRUDqry_pb2 as CRUDqry__pb2


class CRUDqryStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.crudQry = channel.unary_unary(
                '/CRUDqry/crudQry',
                request_serializer=CRUDqry__pb2.CRUDqry_request.SerializeToString,
                response_deserializer=CRUDqry__pb2.CRUDqry_response.FromString,
                )


class CRUDqryServicer(object):
    """Missing associated documentation comment in .proto file."""

    def crudQry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CRUDqryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'crudQry': grpc.unary_unary_rpc_method_handler(
                    servicer.crudQry,
                    request_deserializer=CRUDqry__pb2.CRUDqry_request.FromString,
                    response_serializer=CRUDqry__pb2.CRUDqry_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'CRUDqry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CRUDqry(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def crudQry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/CRUDqry/crudQry',
            CRUDqry__pb2.CRUDqry_request.SerializeToString,
            CRUDqry__pb2.CRUDqry_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
