# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import cache_pb2 as cache__pb2


class cacheStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createCache = channel.unary_unary(
                '/cache/createCache',
                request_serializer=cache__pb2.createDelete_request.SerializeToString,
                response_deserializer=cache__pb2.createDelete_response.FromString,
                )
        self.deleteCache = channel.unary_unary(
                '/cache/deleteCache',
                request_serializer=cache__pb2.createDelete_request.SerializeToString,
                response_deserializer=cache__pb2.createDelete_response.FromString,
                )


class cacheServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cacheServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createCache': grpc.unary_unary_rpc_method_handler(
                    servicer.createCache,
                    request_deserializer=cache__pb2.createDelete_request.FromString,
                    response_serializer=cache__pb2.createDelete_response.SerializeToString,
            ),
            'deleteCache': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteCache,
                    request_deserializer=cache__pb2.createDelete_request.FromString,
                    response_serializer=cache__pb2.createDelete_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cache', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class cache(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache/createCache',
            cache__pb2.createDelete_request.SerializeToString,
            cache__pb2.createDelete_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cache/deleteCache',
            cache__pb2.createDelete_request.SerializeToString,
            cache__pb2.createDelete_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
