# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cache.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cache.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x63\x61\x63he.proto\")\n\x14\x63reateDelete_request\x12\x11\n\tcacheName\x18\x01 \x01(\t\"8\n\x15\x63reateDelete_response\x12\r\n\x05\x65rror\x18\x01 \x01(\t\x12\x10\n\x08response\x18\x02 \x01(\t2\x87\x01\n\x05\x63\x61\x63he\x12>\n\x0b\x63reateCache\x12\x15.createDelete_request\x1a\x16.createDelete_response\"\x00\x12>\n\x0b\x64\x65leteCache\x12\x15.createDelete_request\x1a\x16.createDelete_response\"\x00\x62\x06proto3'
)




_CREATEDELETE_REQUEST = _descriptor.Descriptor(
  name='createDelete_request',
  full_name='createDelete_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cacheName', full_name='createDelete_request.cacheName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=56,
)


_CREATEDELETE_RESPONSE = _descriptor.Descriptor(
  name='createDelete_response',
  full_name='createDelete_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='error', full_name='createDelete_response.error', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='createDelete_response.response', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=114,
)

DESCRIPTOR.message_types_by_name['createDelete_request'] = _CREATEDELETE_REQUEST
DESCRIPTOR.message_types_by_name['createDelete_response'] = _CREATEDELETE_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

createDelete_request = _reflection.GeneratedProtocolMessageType('createDelete_request', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDELETE_REQUEST,
  '__module__' : 'cache_pb2'
  # @@protoc_insertion_point(class_scope:createDelete_request)
  })
_sym_db.RegisterMessage(createDelete_request)

createDelete_response = _reflection.GeneratedProtocolMessageType('createDelete_response', (_message.Message,), {
  'DESCRIPTOR' : _CREATEDELETE_RESPONSE,
  '__module__' : 'cache_pb2'
  # @@protoc_insertion_point(class_scope:createDelete_response)
  })
_sym_db.RegisterMessage(createDelete_response)



_CACHE = _descriptor.ServiceDescriptor(
  name='cache',
  full_name='cache',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=117,
  serialized_end=252,
  methods=[
  _descriptor.MethodDescriptor(
    name='createCache',
    full_name='cache.createCache',
    index=0,
    containing_service=None,
    input_type=_CREATEDELETE_REQUEST,
    output_type=_CREATEDELETE_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteCache',
    full_name='cache.deleteCache',
    index=1,
    containing_service=None,
    input_type=_CREATEDELETE_REQUEST,
    output_type=_CREATEDELETE_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CACHE)

DESCRIPTOR.services_by_name['cache'] = _CACHE

# @@protoc_insertion_point(module_scope)
