# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tableCRUD.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tableCRUD.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ftableCRUD.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xcd\x01\n\x13\x63reateTable_request\x12\x10\n\x08pageSize\x18\x01 \x01(\x05\x12\x11\n\tcacheName\x18\x02 \x01(\t\x12\x11\n\ttableName\x18\x03 \x01(\t\x12\x1f\n\x17\x63olumn_1_primarykey_int\x18\x04 \x01(\t\x12\x15\n\rcolumn_2_date\x18\x05 \x01(\t\x12\x17\n\x0f\x63olumn_3_string\x18\x06 \x01(\t\x12\x17\n\x0f\x63olumn_4_string\x18\x07 \x01(\t\x12\x14\n\x0c\x63olumn_5_int\x18\x08 \x01(\t\"v\n\x14\x63reateTable_response\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\t\x12\"\n\x0bschema_data\x18\x03 \x03(\x0b\x32\r.table_schema\x12\x12\n\x05\x65rror\x18\x04 \x01(\tH\x00\x88\x01\x01\x42\x08\n\x06_error\"@\n\x0ctable_schema\x12\x30\n\x0fmetadata_fields\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"M\n\x13\x64\x65leteTable_request\x12\x11\n\tcacheName\x18\x01 \x01(\t\x12\x11\n\ttableName\x18\x02 \x01(\t\x12\x10\n\x08pageSize\x18\x03 \x01(\x05\x32\x8b\x01\n\ttableCRUD\x12>\n\rcreatingTable\x12\x14.createTable_request\x1a\x15.createTable_response\"\x00\x12>\n\rdeletingTable\x12\x14.deleteTable_request\x1a\x15.createTable_response\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_CREATETABLE_REQUEST = _descriptor.Descriptor(
  name='createTable_request',
  full_name='createTable_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='createTable_request.pageSize', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cacheName', full_name='createTable_request.cacheName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tableName', full_name='createTable_request.tableName', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column_1_primarykey_int', full_name='createTable_request.column_1_primarykey_int', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column_2_date', full_name='createTable_request.column_2_date', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column_3_string', full_name='createTable_request.column_3_string', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column_4_string', full_name='createTable_request.column_4_string', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column_5_int', full_name='createTable_request.column_5_int', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=255,
)


_CREATETABLE_RESPONSE = _descriptor.Descriptor(
  name='createTable_response',
  full_name='createTable_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='createTable_response.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='createTable_response.data', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='schema_data', full_name='createTable_response.schema_data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='createTable_response.error', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_error', full_name='createTable_response._error',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=257,
  serialized_end=375,
)


_TABLE_SCHEMA = _descriptor.Descriptor(
  name='table_schema',
  full_name='table_schema',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata_fields', full_name='table_schema.metadata_fields', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=377,
  serialized_end=441,
)


_DELETETABLE_REQUEST = _descriptor.Descriptor(
  name='deleteTable_request',
  full_name='deleteTable_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cacheName', full_name='deleteTable_request.cacheName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tableName', full_name='deleteTable_request.tableName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='deleteTable_request.pageSize', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=520,
)

_CREATETABLE_RESPONSE.fields_by_name['schema_data'].message_type = _TABLE_SCHEMA
_CREATETABLE_RESPONSE.oneofs_by_name['_error'].fields.append(
  _CREATETABLE_RESPONSE.fields_by_name['error'])
_CREATETABLE_RESPONSE.fields_by_name['error'].containing_oneof = _CREATETABLE_RESPONSE.oneofs_by_name['_error']
_TABLE_SCHEMA.fields_by_name['metadata_fields'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['createTable_request'] = _CREATETABLE_REQUEST
DESCRIPTOR.message_types_by_name['createTable_response'] = _CREATETABLE_RESPONSE
DESCRIPTOR.message_types_by_name['table_schema'] = _TABLE_SCHEMA
DESCRIPTOR.message_types_by_name['deleteTable_request'] = _DELETETABLE_REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

createTable_request = _reflection.GeneratedProtocolMessageType('createTable_request', (_message.Message,), {
  'DESCRIPTOR' : _CREATETABLE_REQUEST,
  '__module__' : 'tableCRUD_pb2'
  # @@protoc_insertion_point(class_scope:createTable_request)
  })
_sym_db.RegisterMessage(createTable_request)

createTable_response = _reflection.GeneratedProtocolMessageType('createTable_response', (_message.Message,), {
  'DESCRIPTOR' : _CREATETABLE_RESPONSE,
  '__module__' : 'tableCRUD_pb2'
  # @@protoc_insertion_point(class_scope:createTable_response)
  })
_sym_db.RegisterMessage(createTable_response)

table_schema = _reflection.GeneratedProtocolMessageType('table_schema', (_message.Message,), {
  'DESCRIPTOR' : _TABLE_SCHEMA,
  '__module__' : 'tableCRUD_pb2'
  # @@protoc_insertion_point(class_scope:table_schema)
  })
_sym_db.RegisterMessage(table_schema)

deleteTable_request = _reflection.GeneratedProtocolMessageType('deleteTable_request', (_message.Message,), {
  'DESCRIPTOR' : _DELETETABLE_REQUEST,
  '__module__' : 'tableCRUD_pb2'
  # @@protoc_insertion_point(class_scope:deleteTable_request)
  })
_sym_db.RegisterMessage(deleteTable_request)



_TABLECRUD = _descriptor.ServiceDescriptor(
  name='tableCRUD',
  full_name='tableCRUD',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=523,
  serialized_end=662,
  methods=[
  _descriptor.MethodDescriptor(
    name='creatingTable',
    full_name='tableCRUD.creatingTable',
    index=0,
    containing_service=None,
    input_type=_CREATETABLE_REQUEST,
    output_type=_CREATETABLE_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deletingTable',
    full_name='tableCRUD.deletingTable',
    index=1,
    containing_service=None,
    input_type=_DELETETABLE_REQUEST,
    output_type=_CREATETABLE_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TABLECRUD)

DESCRIPTOR.services_by_name['tableCRUD'] = _TABLECRUD

# @@protoc_insertion_point(module_scope)
