# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cacheMetrics.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cacheMetrics.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x63\x61\x63heMetrics.proto\x1a\x1cgoogle/protobuf/struct.proto\"6\n\x0fmetrics_request\x12\x11\n\tcacheName\x18\x01 \x01(\t\x12\x10\n\x08pageSize\x18\x02 \x01(\x05\"O\n\x10metrics_response\x12\r\n\x05reads\x18\x01 \x01(\x05\x12\x0e\n\x06writes\x18\x02 \x01(\x05\x12\x0c\n\x04hits\x18\x03 \x01(\x05\x12\x0e\n\x06misses\x18\x04 \x01(\x05\"\x12\n\x10metadata_request\"O\n\x11metadata_response\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x1b\n\x08metadata\x18\x03 \x03(\x0b\x32\t.metadata\"<\n\x08metadata\x12\x30\n\x0fmetadata_fields\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"$\n\rshow_response\x12\x13\n\x0btable_names\x18\x01 \x03(\t2\xab\x01\n\x07metrics\x12\x35\n\x0c\x63\x61\x63heMetrics\x12\x10.metrics_request\x1a\x11.metrics_response\"\x00\x12\x33\n\x08getCache\x12\x11.metadata_request\x1a\x12.metadata_response\"\x00\x12\x34\n\nshowTables\x12\x10.metrics_request\x1a\x12.metadata_response\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_struct__pb2.DESCRIPTOR,])




_METRICS_REQUEST = _descriptor.Descriptor(
  name='metrics_request',
  full_name='metrics_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cacheName', full_name='metrics_request.cacheName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pageSize', full_name='metrics_request.pageSize', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=106,
)


_METRICS_RESPONSE = _descriptor.Descriptor(
  name='metrics_response',
  full_name='metrics_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reads', full_name='metrics_response.reads', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='writes', full_name='metrics_response.writes', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hits', full_name='metrics_response.hits', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='misses', full_name='metrics_response.misses', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=187,
)


_METADATA_REQUEST = _descriptor.Descriptor(
  name='metadata_request',
  full_name='metadata_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=207,
)


_METADATA_RESPONSE = _descriptor.Descriptor(
  name='metadata_response',
  full_name='metadata_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='metadata_response.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='metadata_response.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='metadata_response.metadata', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=288,
)


_METADATA = _descriptor.Descriptor(
  name='metadata',
  full_name='metadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='metadata_fields', full_name='metadata.metadata_fields', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=290,
  serialized_end=350,
)


_SHOW_RESPONSE = _descriptor.Descriptor(
  name='show_response',
  full_name='show_response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_names', full_name='show_response.table_names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=388,
)

_METADATA_RESPONSE.fields_by_name['metadata'].message_type = _METADATA
_METADATA.fields_by_name['metadata_fields'].message_type = google_dot_protobuf_dot_struct__pb2._STRUCT
DESCRIPTOR.message_types_by_name['metrics_request'] = _METRICS_REQUEST
DESCRIPTOR.message_types_by_name['metrics_response'] = _METRICS_RESPONSE
DESCRIPTOR.message_types_by_name['metadata_request'] = _METADATA_REQUEST
DESCRIPTOR.message_types_by_name['metadata_response'] = _METADATA_RESPONSE
DESCRIPTOR.message_types_by_name['metadata'] = _METADATA
DESCRIPTOR.message_types_by_name['show_response'] = _SHOW_RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

metrics_request = _reflection.GeneratedProtocolMessageType('metrics_request', (_message.Message,), {
  'DESCRIPTOR' : _METRICS_REQUEST,
  '__module__' : 'cacheMetrics_pb2'
  # @@protoc_insertion_point(class_scope:metrics_request)
  })
_sym_db.RegisterMessage(metrics_request)

metrics_response = _reflection.GeneratedProtocolMessageType('metrics_response', (_message.Message,), {
  'DESCRIPTOR' : _METRICS_RESPONSE,
  '__module__' : 'cacheMetrics_pb2'
  # @@protoc_insertion_point(class_scope:metrics_response)
  })
_sym_db.RegisterMessage(metrics_response)

metadata_request = _reflection.GeneratedProtocolMessageType('metadata_request', (_message.Message,), {
  'DESCRIPTOR' : _METADATA_REQUEST,
  '__module__' : 'cacheMetrics_pb2'
  # @@protoc_insertion_point(class_scope:metadata_request)
  })
_sym_db.RegisterMessage(metadata_request)

metadata_response = _reflection.GeneratedProtocolMessageType('metadata_response', (_message.Message,), {
  'DESCRIPTOR' : _METADATA_RESPONSE,
  '__module__' : 'cacheMetrics_pb2'
  # @@protoc_insertion_point(class_scope:metadata_response)
  })
_sym_db.RegisterMessage(metadata_response)

metadata = _reflection.GeneratedProtocolMessageType('metadata', (_message.Message,), {
  'DESCRIPTOR' : _METADATA,
  '__module__' : 'cacheMetrics_pb2'
  # @@protoc_insertion_point(class_scope:metadata)
  })
_sym_db.RegisterMessage(metadata)

show_response = _reflection.GeneratedProtocolMessageType('show_response', (_message.Message,), {
  'DESCRIPTOR' : _SHOW_RESPONSE,
  '__module__' : 'cacheMetrics_pb2'
  # @@protoc_insertion_point(class_scope:show_response)
  })
_sym_db.RegisterMessage(show_response)



_METRICS = _descriptor.ServiceDescriptor(
  name='metrics',
  full_name='metrics',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=391,
  serialized_end=562,
  methods=[
  _descriptor.MethodDescriptor(
    name='cacheMetrics',
    full_name='metrics.cacheMetrics',
    index=0,
    containing_service=None,
    input_type=_METRICS_REQUEST,
    output_type=_METRICS_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getCache',
    full_name='metrics.getCache',
    index=1,
    containing_service=None,
    input_type=_METADATA_REQUEST,
    output_type=_METADATA_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='showTables',
    full_name='metrics.showTables',
    index=2,
    containing_service=None,
    input_type=_METRICS_REQUEST,
    output_type=_METADATA_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_METRICS)

DESCRIPTOR.services_by_name['metrics'] = _METRICS

# @@protoc_insertion_point(module_scope)
