# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import cacheMetrics_pb2 as cacheMetrics__pb2


class metricsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.cacheMetrics = channel.unary_unary(
                '/metrics/cacheMetrics',
                request_serializer=cacheMetrics__pb2.metrics_request.SerializeToString,
                response_deserializer=cacheMetrics__pb2.metrics_response.FromString,
                )
        self.getCache = channel.unary_unary(
                '/metrics/getCache',
                request_serializer=cacheMetrics__pb2.metadata_request.SerializeToString,
                response_deserializer=cacheMetrics__pb2.metadata_response.FromString,
                )
        self.showTables = channel.unary_unary(
                '/metrics/showTables',
                request_serializer=cacheMetrics__pb2.metrics_request.SerializeToString,
                response_deserializer=cacheMetrics__pb2.metadata_response.FromString,
                )


class metricsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def cacheMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def showTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_metricsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'cacheMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.cacheMetrics,
                    request_deserializer=cacheMetrics__pb2.metrics_request.FromString,
                    response_serializer=cacheMetrics__pb2.metrics_response.SerializeToString,
            ),
            'getCache': grpc.unary_unary_rpc_method_handler(
                    servicer.getCache,
                    request_deserializer=cacheMetrics__pb2.metadata_request.FromString,
                    response_serializer=cacheMetrics__pb2.metadata_response.SerializeToString,
            ),
            'showTables': grpc.unary_unary_rpc_method_handler(
                    servicer.showTables,
                    request_deserializer=cacheMetrics__pb2.metrics_request.FromString,
                    response_serializer=cacheMetrics__pb2.metadata_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'metrics', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class metrics(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def cacheMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metrics/cacheMetrics',
            cacheMetrics__pb2.metrics_request.SerializeToString,
            cacheMetrics__pb2.metrics_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metrics/getCache',
            cacheMetrics__pb2.metadata_request.SerializeToString,
            cacheMetrics__pb2.metadata_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def showTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/metrics/showTables',
            cacheMetrics__pb2.metrics_request.SerializeToString,
            cacheMetrics__pb2.metadata_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
